In [5]:
# 02 - Data Cleaning & Feature Engineering

This notebook prepares the dataset for modelling by:

- Cleaning inconsistent and missing data
- Filtering irrelevant observations
- Creating per-90 performance metrics
- Engineering meaningful football-specific features

The goal is to create a structured dataset suitable for machine learning models predicting player market value.

SyntaxError: invalid syntax (1424757004.py, line 3)

In [6]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [7]:
df = pd.read_csv("../data/players_with_valuations.csv")

print("Shape:", df.shape)
df.head()

Shape: (2583, 134)

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,G+A-PK,Rk_stats_keeper,Nation_stats_keeper,Pos_stats_keeper,Comp_stats_keeper,Age_stats_keeper,Born_stats_keeper,MP_stats_keeper,Starts_stats_keeper,Min_stats_keeper,90s_stats_keeper,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm,Rk_stats_shooting,Nation_stats_shooting,Pos_stats_shooting,Comp_stats_shooting,Age_stats_shooting,Born_stats_shooting,90s_stats_shooting,Gls_stats_shooting,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK_stats_shooting,PKatt_stats_shooting,Rk_stats_playing_time,Nation_stats_playing_time,Pos_stats_playing_time,Comp_stats_playing_time,Age_stats_playing_time,Born_stats_playing_time,MP_stats_playing_time,Min_stats_playing_time,Mn/MP,Min%,90s_stats_playing_time,Starts_stats_playing_time,Mn/Start,Compl,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off,Rk_stats_misc,Nation_stats_misc,Pos_stats_misc,Comp_stats_misc,Age_stats_misc,Born_stats_misc,90s_stats_misc,CrdY_stats_misc,CrdR_stats_misc,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,clean_name,player_id,first_name,last_name,name,last_season,current_club_id_x,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name_x,market_value_in_eur_x,highest_market_value_in_eur,date,market_value_in_eur_y,current_club_name_y,current_club_id_y,player_club_domestic_competition_id
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,25.0,2000.0,30,24,1975,21.9,4,3,7,4,0,0,1,0,0.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,us USA,"MF,FW",eng Premier League,25-169,2000.0,21.9,4,41,15,36.6,1.87,0.68,0.10,0.27,0,0,1,us USA,"MF,FW",eng Premier League,25-169,2000.0,30,1975,66,70.8,21.9,24,77.0,2,6,21.0,1,1.00,30,26,4,0.18,1.84,1,us USA,"MF,FW",eng Premier League,25-169,2000.0,21.9,1,0,0,17,43,5,35,13,22,0,brenden aaronson,393323,Brenden,Aaronson,Brenden Aaronson,2025,399,brenden-aaronson,United States,"Medford, New Jersey",United States,22/10/2000 00:00,Attacking Midfield,Midfield,right,177.0,30/06/2027 00:00,The.Team,https://img.a.transfermarkt.technology/portrai...,56.0,9.0,NaN,https://www.transfermarkt.co.uk/brenden-aarons...,GB1,Leeds United Association Football Club,18000000,30000000,11/07/2018,50000,Bethlehem Steel FC,51762,NaN
1,2,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,19.0,2006.0,2,1,120,1.3,0,0,0,0,0,0,0,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,eng ENG,DF,eng Premier League,19-331,2006.0,1.3,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0,3,eng ENG,DF,eng Premier League,19-331,2006.0,2,120,60,4.3,1.3,1,75.0,0,1,45.0,11,0.00,0,4,-4,-3.00,-2.73,2,eng ENG,DF,eng Premier League,19-331,2006.0,1.3,0,0,0,2,1,0,3,2,2,0,zach abbott,933017,Zach,Abbott,Zach Abbott,2025,703,zach-abbott,NaN,NaN,England,13/05/2006 00:00,Centre-Back,Defender,right,180.0,30/06/2029 00:00,CAA Stellar,https://img.a.transfermarkt.technology/portrai...,2.0,0.0,NaN,https://www.transfermarkt.co.uk/zach-abbott/pr...,GB1,Nottingham Forest Football Club,3000000,3000000,03/11/2022,250000,Nottingham Forest U18,12799,NaN
2,3,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,20.0,2006.0,20,4,638,7.1,2,0,2,2,0,0,0,0,0.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,ma MAR,"MF,FW",es La Liga,20-087,2006.0,7.1,2,16,4,25.0,2.26,0.56,0.13,0.50,0,0,5,ma MAR,"MF,FW",es La Liga,20-087,2006.0,20,638,32,23.6,7.1,4,75.0,1,16,21.0,10,1.55,16,11,5,0.71,0.62,3,ma MAR,"MF,FW",es La Liga,20-087,2006.0,7.1,0,0,0,5,3,2,26,3,3,0,jones el-abdellaoui,960571,Jones,El-Abdellaoui,Jones El-Abdellaoui,2025,940,jones-el-abdellaoui,Norway,Oslo,Morocco,12/01/2006 00:00,Right Winger,Attack,right,184.0,30/06/2029 00:00,Keypass AS,https://img.a.transfermarkt.technology/portrai...,1.0,0.0,NaN,https://www.transfermarkt.co.uk/jones-el-abdel...,ES1,Real Club Celta de Vigo S. A. D.,8000000,8000000,01/07/2022,50000,Vålerenga Fotball Elite,76,NO1
3,4,Himad Abdelli,dz ALG,"FW,MF",Marseille,fr Ligue 1,26.0,1999.0,5,0,69,0.8,0,0,0,0,0,0,1,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,dz ALG,"FW,MF",fr Ligue 1,26-143,1999.0,0.8,0,3,1,33.3,3.91,1.30,0.00,0.00,0,0,6,dz ALG,"FW,MF",fr Ligue 1,26-143,1999.0,5,69,14,2.7,0.8,0,NaN,0,5,14.0,2,0.80,1,5,-4,-5.22,-6.03,4,dz ALG,"FW,MF",fr Ligue 1,26-143,1999.0,0.8,1,0,0,3,0,0,1,1,1,0,himad abdelli,592979,Himad,Abdelli,Himad Abdelli,2025,244,himad-abdelli,France,Montivilliers,Algeria,17/11/1999 00:00,Attacking Midfield,Midfield,right,185.0,30/06/2030 00:00,One Team Management,https://img.a.transfermarkt.technology/portrai...,8.0,0.0,NaN,https://www.transfermarkt.co.uk/himad-abdelli/...,FR1,Olympique de Marseille,7000000,7000000,08/01/2019,400000,Unknown,244,FR1
4,5,Himad Abdelli,dz ALG,MF,Angers,fr Ligue 1,26.0,1999.0,13,11,943,10.5,2,0,2,0,2,2,1,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,dz ALG,MF,fr Ligue 1,26-143,1999.0,10.5,2,11,5,45.5,1.05,0.48,0.00,0.00,2,2,7,dz ALG,MF,fr Ligue 1,26-143,1999.0,13,943,73,37.4,10.5,11,81.0,4,2,25.0,0,1.38,12,13,-1,-0.10,0.59,5,dz ALG,MF,fr Ligue 1,26-143,1999.0,10.5,1,0,0,16,12,1,9,13,17,0,himad abdelli,592979,Himad,Abdelli,Himad Abdelli,2025,244,himad-abdelli,France,Montivilliers,Algeria,17/11/1999 00:00,Attacking Midfield,Midfield,right,185.0,30/06/2030 00:00,One Team Management,https://img.a.transfermarkt.technology/portrai...,8.0,0.0,NaN,https://www.transfermarkt.co.uk/himad-abdelli/...,FR1,Olympique de Marseille,7000000,7000000,08/01/2019,400000,Unknown,244,FR1

In [8]:
# Remove duplicates
df = df.drop_duplicates()

print("After removing duplicates:", df.shape)

After removing duplicates: (2583, 134)

In [9]:
# Minutes played
df["Min"] = df["Min"].astype(str).str.replace(",", "")
df["Min"] = pd.to_numeric(df["Min"], errors="coerce")

# Age
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

# 90s
df["90s"] = pd.to_numeric(df["90s"], errors="coerce")

In [10]:
# Remove low-minute players
df = df[df["Min"] >= 500]

print("After filtering low-minute players:", df.shape)

After filtering low-minute players: (1761, 134)

In [11]:
missing = df.isnull().sum().sort_values(ascending=False)
missing.head(20)

current_national_team_id    1711
GA90                        1637
W                           1637
Save%                       1637
Rk_stats_keeper             1637
SoTA                        1637
D                           1637
PKm                         1637
PKsv                        1637
PKA                         1637
PKatt_stats_keeper          1637
CS%                         1637
GA                          1637
Saves                       1637
Min_stats_keeper            1637
Starts_stats_keeper         1637
MP_stats_keeper             1637
Born_stats_keeper           1637
Age_stats_keeper            1637
Comp_stats_keeper           1637
dtype: int64

In [12]:
# Simple strategy (safe for now)
df = df.fillna(0)

In [13]:
stat_cols = ["Gls", "Ast", "Sh", "SoT"]

for col in stat_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

In [16]:
for col in stat_cols:
    if col in df.columns:
        df[f"{col}_per90"] = df[col] / df["90s"]

In [17]:
# Goal contribution
df["goal_contribution"] = df["Gls"] + df["Ast"]

# Goal contribution per 90
df["goal_contribution_per90"] = df["goal_contribution"] / df["90s"]

# Shooting accuracy
df["shot_accuracy"] = df["SoT"] / df["Sh"]

In [19]:
# Simple attacking score
df["attacking_score"] = (
    df["Gls_per90"] * 0.5 +
    df["Ast_per90"] * 0.3 +
    df["Sh_per90"] * 0.2
)

In [21]:
def simplify_position(pos):
    if "GK" in pos:
        return "GK"
    elif "DF" in pos:
        return "DEF"
    elif "MF" in pos:
        return "MID"
    elif "FW" in pos:
        return "FWD"
    else:
        return "OTHER"

df["position_group"] = df["Pos"].apply(simplify_position)

In [22]:
df = pd.get_dummies(df, columns=["Comp"], drop_first=False)

In [23]:
print("Final dataset shape:", df.shape)
df.head()

Final dataset shape: (1761, 147)

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,G+A-PK,Rk_stats_keeper,Nation_stats_keeper,Pos_stats_keeper,Comp_stats_keeper,Age_stats_keeper,Born_stats_keeper,MP_stats_keeper,Starts_stats_keeper,Min_stats_keeper,90s_stats_keeper,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm,Rk_stats_shooting,Nation_stats_shooting,Pos_stats_shooting,Comp_stats_shooting,Age_stats_shooting,Born_stats_shooting,90s_stats_shooting,Gls_stats_shooting,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK_stats_shooting,PKatt_stats_shooting,Rk_stats_playing_time,Nation_stats_playing_time,Pos_stats_playing_time,Comp_stats_playing_time,Age_stats_playing_time,Born_stats_playing_time,MP_stats_playing_time,Min_stats_playing_time,Mn/MP,Min%,90s_stats_playing_time,Starts_stats_playing_time,Mn/Start,Compl,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off,Rk_stats_misc,Nation_stats_misc,Pos_stats_misc,Comp_stats_misc,Age_stats_misc,Born_stats_misc,90s_stats_misc,CrdY_stats_misc,CrdR_stats_misc,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,clean_name,player_id,first_name,last_name,name,last_season,current_club_id_x,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name_x,market_value_in_eur_x,highest_market_value_in_eur,date,market_value_in_eur_y,current_club_name_y,current_club_id_y,player_club_domestic_competition_id,Gls_per90,Ast_per90,Sh_per90,SoT_per90,goal_contribution,goal_contribution_per90,shot_accuracy,attacking_score,position_group,Comp_de Bundesliga,Comp_eng Premier League,Comp_es La Liga,Comp_fr Ligue 1,Comp_it Serie A
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,25.0,2000.0,30,24,1975,21.9,4,3,7,4,0,0,1,0,0.32,0.0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,us USA,"MF,FW",eng Premier League,25-169,2000.0,21.9,4,41,15,36.6,1.87,0.68,0.10,0.27,0,0,1,us USA,"MF,FW",eng Premier League,25-169,2000.0,30,1975,66,70.8,21.9,24,77.0,2,6,21.0,1,1.00,30,26,4,0.18,1.84,1,us USA,"MF,FW",eng Premier League,25-169,2000.0,21.9,1,0,0,17,43,5,35,13,22,0,brenden aaronson,393323,Brenden,Aaronson,Brenden Aaronson,2025,399,brenden-aaronson,United States,"Medford, New Jersey",United States,22/10/2000 00:00,Attacking Midfield,Midfield,right,177.0,30/06/2027 00:00,The.Team,https://img.a.transfermarkt.technology/portrai...,56.0,9.0,0.0,https://www.transfermarkt.co.uk/brenden-aarons...,GB1,Leeds United Association Football Club,18000000,30000000,11/07/2018,50000,Bethlehem Steel FC,51762,0,0.182648,0.136986,1.872146,0.684932,7,0.319635,0.365854,0.506849,MID,False,True,False,False,False
2,3,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,20.0,2006.0,20,4,638,7.1,2,0,2,2,0,0,0,0,0.28,0.0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,ma MAR,"MF,FW",es La Liga,20-087,2006.0,7.1,2,16,4,25.0,2.26,0.56,0.13,0.50,0,0,5,ma MAR,"MF,FW",es La Liga,20-087,2006.0,20,638,32,23.6,7.1,4,75.0,1,16,21.0,10,1.55,16,11,5,0.71,0.62,3,ma MAR,"MF,FW",es La Liga,20-087,2006.0,7.1,0,0,0,5,3,2,26,3,3,0,jones el-abdellaoui,960571,Jones,El-Abdellaoui,Jones El-Abdellaoui,2025,940,jones-el-abdellaoui,Norway,Oslo,Morocco,12/01/2006 00:00,Right Winger,Attack,right,184.0,30/06/2029 00:00,Keypass AS,https://img.a.transfermarkt.technology/portrai...,1.0,0.0,0.0,https://www.transfermarkt.co.uk/jones-el-abdel...,ES1,Real Club Celta de Vigo S. A. D.,8000000,8000000,01/07/2022,50000,Vålerenga Fotball Elite,76,NO1,0.281690,0.000000,2.253521,0.563380,2,0.281690,0.250000,0.591549,MID,False,False,True,False,False
4,5,Himad Abdelli,dz ALG,MF,Angers,26.0,1999.0,13,11,943,10.5,2,0,2,0,2,2,1,0,0.00,0.0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5,dz ALG,MF,fr Ligue 1,26-143,1999.0,10.5,2,11,5,45.5,1.05,0.48,0.00,0.00,2,2,7,dz ALG,MF,fr Ligue 1,26-143,1999.0,13,943,73,37.4,10.5,11,81.0,4,2,25.0,0,1.38,12,13,-1,-0.10,0.59,5,dz ALG,MF,fr Ligue 1,26-143,1999.0,10.5,1,0,0,16,12,1,9,13,17,0,himad abdelli,592979,Himad,Abdelli,Himad Abdelli,2025,244,himad-abdelli,France,Montivilliers,Algeria,17/11/1999 00:00,Attacking Midfield,Midfield,right,185.0,30/06/2030 00:00,One Team Management,https://img.a.transfermarkt.technology/portrai...,8.0,0.0,0.0,https://www.transfermarkt.co.uk/himad-abdelli/...,FR1,Olympique de Marseille,7000000,7000000,08/01/2019,400000,Unknown,244,FR1,0.190476,0.000000,1.047619,0.476190,2,0.190476,0.454545,0.304762,MID,False,False,False,True,False
5,6,Ali Abdi,tn TUN,"DF,MF",Nice,32.0,1993.0,17,11,955,10.6,1,0,1,1,0,0,4,1,0.09,0.0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6,tn TUN,"DF,MF",fr Ligue 1,32-110,1993.0,10.6,1,5,1,20.0,0.47,0.09,0.20,1.00,0,0,8,tn TUN,"DF,MF",fr Ligue 1,32-110,1993.0,17,955,56,37.9,10.6,11,74.0,6,6,24.0,1,0.65,16,15,1,0.09,1.42,6,tn TUN,"DF,MF",fr Ligue 1,32-110,1993.0,10.6,4,1,1,16,14,0,28,10,8,0,ali abdi,211474,Ali,Abdi,Ali Abdi,2025,417,ali-abdi,Tunisia,Sfax,Tunisia,20/12/1993 00:00,Left-Back,Defender,left,183.0,30/06/2027 00:00,Scuderia,https://img.a.transfermarkt.technology/portrai...,44.0,7.0,0.0,https://www.transfermarkt.co.uk/ali-abdi/profi...,FR1,Olympique Gymnaste Club Nice Côte d'Azur,2500000,3000000,11/04/2012,75000,JS Kairouanaise,17534,0,0.094340,0.000000,0.471698,0.094340,1,0.094340,0.200000,0.141509,DEF,False,False,False,True,False
6,7,Salis Abdul Samed,gh GHA,MF,Nice,26.0,2000.0,14,9,663,7.4,0,0,0,0,0,0,3,0,0.00,0.0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7,gh GHA,MF,fr Ligue 1,26-014,2000.0,7.4,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,9,gh GHA,MF,fr Ligue 1,26-014,2000.0,14,663,47,26.3,7.4,9,64.0,1,5,17.0,10,1.14,13,15,-2,-0.27,0.70,7,gh GHA,MF,fr Ligue 1,26-014,2000.0,7.4,3,0,0,14,7,0,1,9,7,0,salis abdul samed,688707,Salis,Abdul Samed,Salis Abdul Samed,2025,417,salis-abdul-samed,Ghana,Accra,Ghana,26/03/2000 00:00,Defensive Midfield,Midfield,right,179.0,30/06/2028 00:00,Supernova Management,https://img.a.transfermarkt.technology/portrai...,22.0,0.0,0.0,https://www.transfermarkt.co.uk/salis-abdul-sa...,FR1,Olympique Gymnaste Club Nice Côte d'Azur,4500000,18000000,30/09/2019,150000,Clermont Foot 63,3524,FR1,0.000000,0.000000,0.000000,0.000000,0,0.000000,NaN,0.000000,MID,False,False,False,True,False

In [24]:
df.to_csv("../data/cleaned_players_dataset.csv", index=False)

print("Cleaned dataset saved.")

Cleaned dataset saved.